<?php

/**
 * Autogenerated base class for the Users model.
 * 
 * Don't change this file, since it can be overwritten.
 * Instead, change the Users.php file.
 *
 * @module Users
 */
/**
 * Base class for the Users model
 * @class Base_Users
 */
abstract class Base_Users
{
	/**
	 * The list of model classes
	 * @property $table_classnames
	 * @type array
	 */
	static $table_classnames = array (
  0 => 'Users_Capability',
  1 => 'Users_Contact',
  2 => 'Users_Device',
  3 => 'Users_Email',
  4 => 'Users_ExternalFrom',
  5 => 'Users_ExternalTo',
  6 => 'Users_Field',
  7 => 'Users_Identify',
  8 => 'Users_Intent',
  9 => 'Users_Label',
  10 => 'Users_Link',
  11 => 'Users_Mobile',
  12 => 'Users_Permission',
  13 => 'Users_Quota',
  14 => 'Users_Referred',
  15 => 'Users_Session',
  16 => 'Users_Total',
  17 => 'Users_User',
  18 => 'Users_Vote',
  19 => 'Users_Web3',
  20 => 'Users_Web3Transaction',
);

	/**
     * This method calls Db.connect() using information stored in the configuration.
     * If this has already been called, then the same db object is returned.
	 * @method db
	 * @return {Db_Interface} The database object
	 */
	static function db()
	{
		return Db::connect('Users');
	}

	/**
	 * The connection name for the class
	 * @method connectionName
	 * @return {string} The name of the connection
	 */
	static function connectionName()
	{
		return 'Users';
	}
};