"use strict";
/*jshint node:true */
/**
 * Users plugin
 * @module Users
 * @main Users
 */
var Q = require('Q');
var Users = require('Users');

// Lives here rather than in Users.js: this file is the only user of it, and
// leaving it there made every reference below a ReferenceError, since it was
// a module-local var and never exported.
var timeouts = {};

/**
 * Replacements for Q.Socket methods, use these instead.
 * They implement logic involving sockets, users, sessions, devices, and more.
 * @class Users.Socket
 */
Users.Socket = {

	/**
	 * Socket clients keyed by topicId
	 */
	clients: {},

	/**
	 * Start http server if needed, and start listening to socket.
	 * Use this instead of Q.Socket
	 * This also attaches a few event handlers for Users events.
	 * @method listen
	 * @param {Object} options Can be any options for the server.listen() in socket.io,
	 *    as well as the following options:
	 * @param {Object} options.host Set the hostname to listen on
	 * @param {Object} options.port Set the port to listen on
	 * @param {Object} options.https If you use https, pass https options here (see Q.listen)
	 * @return {socket.io}
	 */
	listen: function (options) {
		var socket = Q.Socket.listen(options);

		if (!socket) {
			console.warn("Users.listen: socket missing");
			return null;
		}

		socket.io.of('/Q').use(function (client, next) {
			// NOTE: the Q.Socket middleware already ran, and set
			// client.capability to the capability object.
			// Since the capability was successfully verified,
			// the userId must have been generated by the PHP server,
			// so we trust it.
			// A capability minted by Users_Intent::capability() carries the
			// intent token. Q_Capability::toArray() FLATTENS data to the top
			// level -- hence capability.token, not capability.data.token, the
			// same way userId is read below. This has to run before the
			// anonymous early return, because an anonymous client waiting on
			// an intent is exactly who needs the topic.
			var itoken = client.capability && client.capability.token;
			if (itoken && Users.Socket.authorize(client, 'Users/intent/' + itoken)) {
				Users.Socket.join(client, 'Users/intent/' + itoken);
			}

			var userId = client.capability && client.capability.userId;
			if (!userId) {
				return next(); // user is not logged in
			}
			if (!Users.clients[userId]) {
				Users.clients[userId] = {};
			}
			var wasOnline = !Q.isEmpty(Users.User.clientsOnline(userId));
			client.userId = userId;
			client.clientId = client.id;
			Users.clients[userId][client.id] = client;
			if (timeouts[userId]) {
				clearTimeout(timeouts[userId]);
			}
			delete timeouts[userId];
			/**
			 * User has connected.
			 * Reconnections before disconnect timeout don't count.
			 * @event connected
			 * @param {Socket} client
			 *	The connecting client. Contains userId, clientId
			 * @param {Boolean} online
			 *	Whether any other clients were online for the user before this
			 */
			Users.emit('connected', client, wasOnline);
			if (wasOnline) {
				Q.log('New client connected: ' + userId + '('+client.id+')');
			} else {
				Q.log('User connected: ' + client.userId);
			}
			next();
		});
		socket.io.of('/Q').on('connection', function(client) {
			if (client.alreadyListeningUsers) {
				return;
			}
			client.alreadyListeningUsers = true;
			client.on('Users/clients', function (callback) {
				var userId = client.capability && client.capability.userId;
				if (!userId) {
					callback(null);
				}
				var oci = {};
				for (var cid in Users.clients[userId]){
					var c = Users.clients[userId][cid];
					oci[cid] = {
						clientId: c.clientId
					};
				}
				callback({
					clients: oci
				});
			});
			client.on('Users/online', function (options, callback) {
				var ret = {};
				for (var userId in Users.clients) {
					ret[userId] = {};
					for (var clientId in Users.clients[userId]) {
						ret[userId][clientId] = true;
					}
				}
				callback(Users.clients);
			});
			client.on('Users/Socket/join', function (topicId, callback) {
				if (!Users.Socket.authorize(client, topicId)) {
					return callback && callback({ error: 'Not authorized' });
				}
				Users.Socket.join(client, topicId);
				callback && callback({ joined: topicId });
			});
			client.on('Users/Socket/leave', function (topicId, callback) {
				Users.Socket.leave(client, topicId);
				callback && callback({ left: topicId });
			});
			client.on('disconnect', function(){
				// before the early return below: an anonymous client never gets
				// client.userId, so leaving this after it leaked that client's
				// entry in Users.Socket.clients forever -- and the intent
				// client is exactly that case
				for (var tid in Users.Socket.clients) {
					if (Users.Socket.clients[tid][client.id]) {
						Users.Socket.leave(client, tid);
					}
				}
				var userId = client.userId;
				var i;
				if (!userId || !Users.clients[userId]) {
					return;
				}
				var clients = Users.clients[userId];
				delete clients[this.id];
				Q.log('Client disconnected: ' + userId + "(" + this.id + ")");
				if (Q.isEmpty(clients)) {
					// All the clients have been disconnected.
					// Let's wait a bit and if none of them reconnect within the timeout period,
					// we'll post a message saying the user disconnected.
					timeouts[userId] = setTimeout(function () {
						if (Q.isEmpty(clients)) {
							/**
							 * User has disconnected, and timeout for reconnection has passed
							 * @event disconnected
							 * @param {String} userId id of the user that disconnected
							 */
							Users.emit('disconnected', userId);
						}
						delete timeouts[userId];
					}, Q.Config.get(["Users", "socket", "disconnectTimeout"], 1000));
				}
			});
		});
		return socket;
	},


	/**
	 * Get all the socket clients that a room has online
	 * @method clientsOnline
	 * @static
	 * @param {String} topicId The id of a topic
	 * @param {String} [sessionId] Optionally provide a session id, to filter clients by
	 * @return {Object} Contains {clientId: client} pairs
	 */
	clientsOnline: function(topicId, sessionId) {
		var clients = Users.Socket.clients[topicId] || {};
		if (!sessionId) {
			return clients;
		}
		var result = {};
		for (var cid in clients) {
			if (clients[cid].sessionId === sessionId) {
				result[cid] = clients[cid];
			}
		}
		return result;
	},
	
	/**
	 * Emits an event to user's socket.io clients that are currently connected
	 * @method emitToUser
	 * @static
	 * @param {String} userId The id of the user
	 * @param {String} event The name of the event the socket client should emit
	 * @param {Object} data Any data to accompany this event name
	 * @return {Boolean} Whether any socket clients were connected at all
	 */
	emitToUser: function(userId, event, data) {
		var args = Array.prototype.slice.call(arguments, 1);
		var clients = Users.User.clientsOnline(userId);
		if (Q.isEmpty(clients)) {
			return false;
		}
		for (var cid in clients) {
			var client = clients[cid];
			client && client.emit.apply(client, args);
		}
		return true;
	},

	/**
	 * Emits an event to room's socket.io clients that are currently connected
	 * @method emitToTopic
	 * @static
	 * @param {String} topicId The id of the room
	 * @param {String} event The name of the event the socket client should emit
	 * @param {Object} data Any data to accompany this event name
	 * @return {Boolean} Whether any socket clients were connected at all
	 */
	emitToTopic: function (topicId, event, data) {
		var args = Array.prototype.slice.call(arguments, 1);
		var room = Q.Socket.io.of('/Q').to(topicId);
		room.emit.apply(room, args);
		return !Q.isEmpty(Users.Socket.clients[topicId]);
	},

    /**
	 * Whether this client's capability entitles it to a topic.
	 * Deny by default; plugins opt topics in by handling the event.
	 * @method authorize
	 */
	authorize: function (client, topicId) {
		var c = client.capability;
		if (!c) return false;
		// intents: the token in the signed capability IS the entitlement
		var t = c.token; // flattened by Q_Capability::toArray(), not nested
		if (t && topicId === 'Users/intent/' + t) return true;
		var allowed = false;
		Users.emit('topic/authorize', client, topicId, function (ok) {
			allowed = allowed || !!ok;
		});
		return allowed;
	},

	/**
	 * @method join
	 */
	join: function (client, topicId) {
		client.join(topicId);              // socket.io's own room
		var m = Users.Socket.clients;
		(m[topicId] = m[topicId] || {})[client.id] = client;
		return true;
	},

	/**
	 * @method leave
	 */
	leave: function (client, topicId) {
		client.leave(topicId);
		var m = Users.Socket.clients[topicId];
		if (m) {
			delete m[client.id];
			if (Q.isEmpty(m)) delete Users.Socket.clients[topicId];
		}
	}
};

module.exports = Users.Socket;
